version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "updated-resume-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s2wwzi122rhm"
s3_prefix = "updated-resume-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
